### ISSUE TITLE
exception in dash when there are no data

### ISSUE THREAD

**Issue by javasoze** [dashbase/dashbase-tools#113]
when doing a select, this happens when there is no corresponding data:

```
Traceback (most recent call last):
  File "/usr/local/bin/dash", line 11, in <module>
    load_entry_point('dashbase-tools', 'console_scripts', 'dash')()
  File "/Users/john/github/dashbase/dashbase-tools/tools/dbsql.py", line 116, in main
    prompt.cmdloop('Starting Dashbase console... Press Ctrl+C or input "exit" to exit!')
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 142, in cmdloop
    stop = self.onecmd(line)
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/Users/john/github/dashbase/dashbase-tools/tools/dbsql.py", line 74, in do_select
    return self.exec_select(param)
  File "/Users/john/github/dashbase/dashbase-tools/tools/dbsql.py", line 91, in exec_select
    resultview.print_hits(result["request"]["fields"], result["hits"])
  File "/Users/john/github/dashbase/dashbase-tools/tools/resultview.py", line 295, in print_hits
    print(table.table)
  File "/usr/local/lib/python2.7/site-packages/terminaltables/base_table.py", line 217, in table
    return flatten(self.gen_table(*dimensions))
  File "/usr/local/lib/python2.7/site-packages/terminaltables/build.py", line 151, in flatten
    return '\n'.join(''.join(r) for r in table)
  File "/usr/local/lib/python2.7/site-packages/terminaltables/build.py", line 151, in <genexpr>
    return '\n'.join(''.join(r) for r in table)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 37: ordinal not in range(128)
```

**Comment by SinceJune** [comment]
i can't reproduce it, how could i get binary data returned

**Comment by javasoze** [comment]
closing for now until we can reproduce properly
