### ISSUE TITLE
connection pool is full after monut for a long time

### ISSUE THREAD

**Issue by PureWhiteWu** [dashbase/dashbase-tools#54]
```
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: staging.dashbase.io
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: staging.dashbase.io
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: staging.dashbase.io
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: staging.dashbase.io
WARNING:urllib3.connectionpool:Connection pool is full, discarding connection: staging.dashbase.io
Traceback (most recent call last):
  File "/Users/daniel/.virtualenvs/dashbase-tools/lib/python2.7/site-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/Users/daniel/.virtualenvs/dashbase-tools/lib/python2.7/site-packages/fuse.py", line 693, in readdir
    fip.contents.fh):
  File "/Users/daniel/.virtualenvs/dashbase-tools/lib/python2.7/site-packages/fuse.py", line 972, in __call__
    ret = getattr(self, op)(path, *args)
  File "/Users/daniel/Works/dashbase-tools/tools/dashbase_mnt.py", line 96, in readdir
    self.update_tables()
  File "/Users/daniel/Works/dashbase-tools/tools/dashbase_mnt.py", line 62, in update_tables
    for t in self.client.get_tables():
TypeError: 'NoneType' object is not iterable
Traceback (most recent call last):
  File "/Users/daniel/.virtualenvs/dashbase-tools/lib/python2.7/site-packages/fuse.py", line 495, in _wrapper
    return func(*args, **kwargs) or 0
  File "/Users/daniel/.virtualenvs/dashbase-tools/lib/python2.7/site-packages/fuse.py", line 693, in readdir
    fip.contents.fh):
  File "/Users/daniel/.virtualenvs/dashbase-tools/lib/python2.7/site-packages/fuse.py", line 972, in __call__
    ret = getattr(self, op)(path, *args)
  File "/Users/daniel/Works/dashbase-tools/tools/dashbase_mnt.py", line 96, in readdir
    self.update_tables()
  File "/Users/daniel/Works/dashbase-tools/tools/dashbase_mnt.py", line 62, in update_tables
    for t in self.client.get_tables():
TypeError: 'NoneType' object is not iterable
```

**Comment by PureWhiteWu** [comment]
at this time fuse can not be stopped in a normal way:
![image](https://user-images.githubusercontent.com/3314335/32868953-795b299e-caaf-11e7-9c8f-e2f6d77e7287.png)

shoould use `kill -9` first and then `umount`
