### ISSUE TITLE
terminal width not enough bug

### ISSUE THREAD

**Issue by PureWhiteWu** [dashbase/dashbase-tools#77]
```
$ logtail -a nginx_json@https://staging.dashbase.io:9876 -q "apple" -f agent -n 5
{'fields': ['agent'], 'numResults': 5, 'tableNames': ['nginx_json'], 'query': {'queryStr': 'apple', 'queryType': 'string'}, 'disableHighlight': True, 'timeRangeFilter': {'startTimeInSec': 1511035448.0}}
Traceback (most recent call last):
  File "/Users/daniel/.virtualenvs/dashbase-tools/bin/logtail", line 11, in <module>
    load_entry_point('dashbase-tools', 'console_scripts', 'logtail')()
  File "/Users/daniel/Works/dashbase-tools/tools/logtail.py", line 102, in main
    result = do_query(rpc, dashbase_req, args.hideraw)
  File "/Users/daniel/Works/dashbase-tools/tools/logtail.py", line 28, in do_query
    resultview.print_result(result, req["fields"], not hide_raw)
  File "/Users/daniel/Works/dashbase-tools/tools/resultview.py", line 46, in print_result
    print_hits(fields, hits, True, show_raw)
  File "/Users/daniel/Works/dashbase-tools/tools/resultview.py", line 265, in print_hits
    wrapped_string = '\n'.join(wrap(raw_val, max_width))
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/textwrap.py", line 354, in wrap
    return w.wrap(text)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/textwrap.py", line 329, in wrap
    return self._wrap_chunks(chunks)
  File "/usr/local/Cellar/python/2.7.14/Frameworks/Python.framework/Versions/2.7/lib/python2.7/textwrap.py", line 258, in _wrap_chunks
    raise ValueError("invalid width %r (must be > 0)" % self.width)
ValueError: invalid width -1 (must be > 0)
```
My terminal width is 84.
After I make my terminal wider, this is fixed.

**Comment by PureWhiteWu** [comment]
This also occurs in `dash`.
Should be fixed in #75
